apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: demo-app
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: web
  selector:
    app: nginx
